### ISSUE TITLE
Add option to validate strings that are added  

### ISSUE THREAD

**Issue by shershen08** [matiastucci/vue-input-tag#10]
For example if I change input type like so ```<input v-if="!readOnly" v-bind:placeholder="getPlaceholder()" type="number" ...``` it will accept only numbers and validate it with browser built in functionality.

In HTML5 there are options to match the patterns in the input (http://www.w3schools.com/tags/att_input_pattern.asp).

Do you think this could be a good enhancement? I could provide a PR if you will

**Comment by matiastucci** [comment]
Yeah, this would be nice. Maybe we can add 2 optional props: `type` and `pattern`.
If you can, create a PR (I'm very busy this week). Otherwise next week I can do it.

**Comment by shershen08** [comment]
OK, will do that tonight

**Comment by shershen08** [comment]
Hmm, that may be not that straightforward. Adding `v-bind:type="validateType" ` with code like this:

```
<script>
  let legitType = /date|datetime|email|month|number|tel|text|time|url/;
  export default {
    name: 'InputTag',
    props: {
     ..
      validate: {
        type: String,
        default: 'text',
      }
    },
    beforeMount : function () {
          if(this.validate && legitType.test(this.validate)) {
              this.validateType = this.validate;
          }
    },
    ..
</script>

<template>

...
    <input v-if="!readOnly" v-bind:placeholder="getPlaceholder()" v-bind:type="validateType" v-model="newTag"

```
Results in vue.js core error - **template syntax error <input :type="validateType" v-model="newTag">: v-model does not support dynamic input types. Use v-if branches instead.**. 

Having multiple <input v-if="type='text'" .. <input v-if="type='number'" .. <input v-if="type='tel'" .. etc doesn't look like an elegant solution.

**Comment by matiastucci** [comment]
Hmm, I didn't know this 😕
Yeah, a lots of inputs with `v-if` doesn't seem nice. I'm not sure if there is other way tho...

**Comment by shershen08** [comment]
I see 3 possible ways to tackle this
- custom directive 
- validator hook inside of the adding item logic
- subcomponent with custom render function
I'll update later today

**Comment by shershen08** [comment]
here's a sample implementation with validator hook - https://github.com/shershen08/vue-input-tag/commit/f2089f7735416e8f0c3dc876596c1d9e7faf6010

let me know what you think?

**Comment by matiastucci** [comment]
I tested locally and works good 👍 
Create a PR to `develop` branch and then we can merge it to `master`

**Comment by matiastucci** [comment]
#12
