### ISSUE TITLE
Strange dependencies?

### ISSUE THREAD

**Issue by scniro** [matiastucci/vue-input-tag#106]
Why [are these](https://github.com/matiastucci/vue-input-tag/blob/master/package.json#L35-L36) `dependencies`?

```
"dependencies": {
  "coveralls": "^3.0.2",
  "ferrocarriloeste": "^1.0.1",
  [...]
},
```

These are clear devdeps, can these be moved?

**Comment by matiastucci** [comment]
https://github.com/matiastucci/vue-input-tag/pull/107 fixes it. Thanks.
