### ISSUE TITLE
placeholder not handled

### ISSUE THREAD

**Issue by foxmask** [matiastucci/vue-input-tag#14]
Version of `Vue` I'm using?: 2.2

Version of `vue-input-tag` I'm using?: 0.0.11

when we're using placeholder, whatever we set to it, the [code](https://github.com/matiastucci/vue-input-tag/blob/master/src/InputTag.vue#L73) always set it to blank

**Comment by matiastucci** [comment]
Thanks for reporting it. #15 closes this.

**Comment by foxmask** [comment]
the error is now fixed, but I have 2 notices: 
one from "npm"
one from me :) 

from npm : 
```
(node:15422) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```

from me : 
when I fill the placeholder, the content is truncated by the width of "new-tag"
for exemple I put in data 
```
placeholder: 'here we set some tags',
```
become 'here we set '
