### ISSUE TITLE
Unknown plugin "transform-runtime"

### ISSUE THREAD

**Issue by abdullah-abunada** [matiastucci/vue-input-tag#17]
Version of `Vue` I'm using?: 2

Version of `vue-input-tag` I'm using?: 0.0.11

Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "../node_modules/vue-input-tag/.babelrc" at 0, attempted to resolve relative to "../node_modules/vue-input-tag"

**Comment by joecampo** [comment]
Hi there,

Make sure you have this plugin installed:

```npm install babel-plugin-transform-runtime```
