### ISSUE TITLE
Can't long text in placeholder

### ISSUE THREAD

**Issue by gn-spawn** [matiastucci/vue-input-tag#19]
Version of `Vue` I'm using?: 2.8.1

Version of `vue-input-tag` I'm using?: recent version

<img width="542" alt="2017-07-06 13 37 55" src="https://user-images.githubusercontent.com/9656062/27895817-761e5098-6250-11e7-8ebe-96c479bb7500.png">

**Comment by matiastucci** [comment]
#33 should fix it. Thanks for reporting it!
