### ISSUE TITLE
Make sure to declare reactive data properties in the data option.

### ISSUE THREAD

**Issue by jackengine** [matiastucci/vue-input-tag#20]
Version of `Vue` I'm using?: 2.3.4

Version of `vue-input-tag` I'm using?: 0.0.11

Small [JSFiddle](https://jsfiddle.net) showing the issue: _____

property or method "tagsArray" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

I just added `<input-tag :on-change="callbackMethod" :tags="tagsArray"></input-tag>` line. How can I add callBackMethod and tagsArray. 
I have tried this:
Simple function named callbackMethod or assigning to InputTag.callbackMethod do not work. Also tried binding to InpuTag.props and data.

**Comment by matiastucci** [comment]
You can check how it's being used in the example: https://github.com/matiastucci/vue-input-tag/blob/master/docs/App.vue
