### ISSUE TITLE
Meet errors.

### ISSUE THREAD

**Issue by tolerious** [matiastucci/vue-input-tag#3]
[This is my code](http://codepen.io/tolerious/pen/VmWBdq?editors=1000#0).

But I got this error, do you ever see this?
<img width="973" alt="2016-11-25 2 03 30" src="https://cloud.githubusercontent.com/assets/2922120/20615966/6a22567c-b319-11e6-812b-af8a495b0545.png">

**Comment by matiastucci** [comment]
what version of Vue are you using?

**Comment by matiastucci** [comment]
are you using `vue-loader`?

**Comment by tolerious** [comment]
I use Vue2.1.0 , sure I use vue-loader. This is my config files.

[webpack.config.js](http://paste.ubuntu.com/23531016/)
[package.json](http://paste.ubuntu.com/23531018/)

**Comment by matiastucci** [comment]
weird. Can you run `npm install babel-plugin-transform-runtime babel-preset-es2015 babel-preset-stage-2 --save-dev`, please?

**Comment by tolerious** [comment]
Sure, let me have a try.

**Comment by tolerious** [comment]
@matiastucci it worked.

**Comment by matiastucci** [comment]
cool. You didn't have `babel-preset-stage-2` installed :)
