### ISSUE TITLE
Add tag when clicking tab (configurable key support)

### ISSUE THREAD

**Issue by EvanZ** [matiastucci/vue-input-tag#30]
Just FYI, the demo isn't working.

**Comment by matiastucci** [comment]
the demo page (https://tucci.me/vue-input-tag)? or what demo? Thanks for letting me know

**Comment by EvanZ** [comment]
Yes, the demo page. When I type in a new tag and hit the tab button, the focus just pops out of the field.

**Comment by matiastucci** [comment]
Ah, you need to hit `enter` for that

**Comment by EvanZ** [comment]
Oh! Is that configurable? I think most users expect tab to create a new tag.

**Comment by ianaya89** [comment]
I think we can work in something tu support it. @matiastucci ?

**Comment by matiastucci** [comment]
I just published a new version (0.0.16) with tab support.

As @ianaya89 says, we can work on making it configurable. Maybe pass an array of keys?

**Comment by EvanZ** [comment]
Wow, thanks guys. Really appreciate your effort.
