### ISSUE TITLE
Remove tag button not reactive

### ISSUE THREAD

**Issue by xon52** [matiastucci/vue-input-tag#31]
First of all, great work on this.
I have been struggling to get this to react to the remove call. It does remove items, and will update as soon as I try and enter a new item (or refresh); but immediately after pressing remove the list displayed includes the removed items.
My array is a computed value, which may be the issue; but as it's from a Vuex getter, I don't want to be storing it locally.

My code: [http://imgur.com/a/SBvaM](http://imgur.com/a/SBvaM)

**Comment by xon52** [comment]
Re-compiled and it worked. Sorry.

**Comment by EvanZ** [comment]
I can't get this component to work at all. Not sure what I'm doing wrong.

**Comment by OneX** [comment]
You can use https://vuejs.org/v2/api/#vm-forceUpdate to force re-render, but not sure is it best practice.

Not sure is it good to use prop value of tags, I think vue suggests using 'data' for reactive values.
But this is not cause of your problem.

**Comment by OneX** [comment]
I tested it and this is actually cause of your problem

**Comment by ianaya89** [comment]
I @OneX thanks for your feedback. You are right about the wrong usage of props (mutating them). We are working in a new approach using events regarding mutations and make it compliance with Vue.

**Comment by OneX** [comment]
@ianaya89 I created [fork](https://github.com/OneX/vue-input-tag/commit/0e8fe355692b1cb2bd96be8c74a690fd75523674) with solution already.

**Comment by ianaya89** [comment]
Nice, great work. I think is pretty similar to what we did. We are going to review it and merge as soon as possible.

Thanks for your contribution 🍻👌

**Comment by pykler** [comment]
Any idea when this will be resolved?

**Comment by matiastucci** [comment]
#33 should fix it. Thanks for reporting it!
