### ISSUE TITLE
Auto Adding on ","(188) key. 

### ISSUE THREAD

**Issue by comeondown** [matiastucci/vue-input-tag#32]
Try write tags on Cyrillic. I find out that when i write letter 'б' component automatically triggers to add new tag. This letter stay on same button with ',' on keyboard. 

`v-on:keydown.enter.188.tab.prevent.stop="addNew(newTag)"`

**Comment by mdaliyan** [comment]
This 188 thing on `v-on:keydown.enter.188.tab.prevent.stop="addNew(newTag)"` made the package unusable on Persian/Farsi keyboards. The key presents "و" character in this language.

**Comment by ianaya89** [comment]
@mdaliyan I am not very familiar with this kind of keyboards, any recommendation or suggestion to fix that?

**Comment by matiastucci** [comment]
#45 fixes this

**Comment by mdaliyan** [comment]
thanks, that looks easy to use

``
<input-tag :tags.sync="tagsArray" add-tag-on-keys="[13,9]"></input-tag>
``

**Comment by mdaliyan** [comment]
but wasn't that easier to use `v-model` instead of `tags` property?
```
<input-tag v-model="tagsArray" add-tag-on-keys="[13,9]"></input-tag>
```
