### ISSUE TITLE
I think we can remove the height attribute in vue-input-tag-wrapper class.

### ISSUE THREAD

**Issue by tolerious** [matiastucci/vue-input-tag#4]
If there are too many tags in our dev element, just like this,
<img width="1004" alt="2016-11-25 3 14 21" src="https://cloud.githubusercontent.com/assets/2922120/20617134/05e44888-b322-11e6-9346-e08e3789a628.png">
<img width="223" alt="2016-11-25 3 14 13" src="https://cloud.githubusercontent.com/assets/2922120/20617160/38207416-b322-11e6-829f-df46213db080.png">

We can't display all of the tags, if we remove the `height` attribute in the `vue-input-tag-wrapper` class, then we can see all of the tags.
<img width="1000" alt="2016-11-25 3 17 06" src="https://cloud.githubusercontent.com/assets/2922120/20617168/46787ea0-b322-11e6-9c53-af72495f4808.png">
<img width="248" alt="2016-11-25 3 17 09" src="https://cloud.githubusercontent.com/assets/2922120/20617187/656a7e94-b322-11e6-940a-cc2cd3e4ac9b.png">

**Comment by matiastucci** [comment]
yup, good idea. I just [pushed it](https://github.com/matiastucci/vue-input-tag/commit/a31bafb2d122bacd2598b068059539780407802b).
