### ISSUE TITLE
add name attribute in the input

### ISSUE THREAD

**Issue by bondythegreat** [matiastucci/vue-input-tag#43]
i cannot find how to add name attribute in the input tag?

**Comment by matiastucci** [comment]
#33 should fix it (I added a ref to the input). Thanks for reporting it!

**Comment by MatthiasRMS** [comment]
Hi @matiastucci , I also need to add a name to the input, but I'm not sure how I can do this, and I didn't get how adding the ref should allow me to do so. Would you mind adding a small example on how to add a name to the input to have 

`<input name="example[formname]" type="text" class="new-tag">`
