### ISSUE TITLE
How to override styles or tag template

### ISSUE THREAD

**Issue by zinefer** [matiastucci/vue-input-tag#48]
Version of `Vue` I'm using?:  2.5.13

Version of `vue-input-tag` I'm using?: 1.0.0

Hi there! This is probably a bit of an obvious question but I'm new to vue and I was wondering how I could go about overriding the tag styles or the overall template? I am using bootstrap - if that matters.

**Comment by matiastucci** [comment]
No worries :) Just like "normal" CSS.

  ```
.vue-input-tag-wrapper .input-tag {
    background-color: red !important;
  }
```
