### ISSUE TITLE
Per-tag color when entering color as hex-values

### ISSUE THREAD

**Issue by Jaszkowic** [matiastucci/vue-input-tag#65]
Hey! I am currently using this Vue component in a project where the user can enter colors in the hex-format. To validate the input I am using the `validate` option: `:validate="new RegExp(/^#[0-9a-f]{6}/i)"`. Everything works great. Now I have a feature proposal: It would be really great if the background color of the tag would change the color according to the entered color tag. This could be realized by providing an option that needs to be set explicitly and/or by providing a new entry in the `validators` object, called `colors` or similar that would automatically trigger the "per-tag color". Just an idea, that would be very helpful for me 👍 

Version of `Vue` I'm using?:  2.5.11
Version of `vue-input-tag` I'm using?: 1.0.3

**Comment by matiastucci** [comment]
Hi! thanks for the idea. To be honest this seems a very specific feature mostly for your case only. I don't think is important. But if you want you are welcome to create a PR.
