### ISSUE TITLE
Tags not disappearing

### ISSUE THREAD

**Issue by irelandpaul** [matiastucci/vue-input-tag#7]
I just installed this and its slick! Nice work!

I have one issue, when I delete tags (by clicking X or by pressing backspace), nothing appears to happen. The tags are still there. However, it does delete them from the array.

Two screens below:

They add just fine to the array:
![image](https://cloud.githubusercontent.com/assets/641691/21246767/9d59a286-c2df-11e6-9b26-97e3c0722cd7.png)

They also delete from the array, but do not delete from the input:
![image](https://cloud.githubusercontent.com/assets/641691/21246855/260263de-c2e0-11e6-9bad-618c697391aa.png)

Thank you for help!

**Comment by tolerious** [comment]
Hi, can you put your code to [jsfiddle](https://jsfiddle.net/), because I don't have this issue.

**Comment by matiastucci** [comment]
Which version of `Vue` and `vue-input-tag` are you using? And as @tolerious mentioned, please provide a [JSFiddle](https://jsfiddle.net).

BTW, I just added an [ISSUE_TEMPLATE](https://github.com/matiastucci/vue-input-tag/blob/master/ISSUE_TEMPLATE.md) file.

**Comment by matiastucci** [comment]
@irelandpaul I'll close it for now. Reopen it with the JSFiddle if you want.

**Comment by irelandpaul** [comment]
I figured it out. The array was being reset directly instead of using Vue.set, so it dropped out of being able to be tracked reactively. That caused the field to not update. Now everything is working great. Thank you!

**Comment by xon52** [comment]
@irelandpaul I see that's the problem, so how did you get it to work?
