### ISSUE TITLE
Read-only on a single tag ?

### ISSUE THREAD

**Issue by bouchezb** [matiastucci/vue-input-tag#73]
Hello, 

I'm looking for a way to set a single tag as read only.
Currently, the read only property is on the input field.

By now, the only way i found to do this, is to currently watch my tags and reinject the value i don't want to be deleted.
I'm looking for a smarter solution also with CSS styling support.

Regards

**Comment by matiastucci** [comment]
Hi! I understand but currently is not possible and tbh I'm not planning on implementing this. Feel free to open a PR tho 👍
