### ISSUE TITLE
Change event

### ISSUE THREAD

**Issue by MartinKravec** [matiastucci/vue-input-tag#75]
Version of `Vue` I'm using?: 2.5.16
Version of `vue-input-tag` I'm using?: 1.0.3

Hello, 

is it possible to set onchange event? How?
This event will not fire on change.

`<input-tag :tags.sync="statistics.values"
                             @change="refreshStatistics"></input-tag>`

Thanks

**Comment by DivyarajB** [comment]
It will be great if we can emit some events which system can do for post process operations.

**Comment by matiastucci** [comment]
You can do this: `<input-tag :tags="tagsArray" @update:tags="refreshStatistics"></input-tag>`
