### ISSUE TITLE
OnPaste Comma delimited list of tags (Common Tagsinput feature)

### ISSUE THREAD

**Issue by imjakechapman** [matiastucci/vue-input-tag#76]
Version of `Vue` I'm using?: V2.5.16
Version of `vue-input-tag` I'm using?: V1.0.4

Title is self explanatory. How can we handle the pasting of a comma delimited list of tags

example list `tag-one, tag-two, tag-three, tag-four`

Paste and it just becomes one large tag instead of multiple individual tags for each of the list.

**Comment by matiastucci** [comment]
We can add a `onAddTag` method like this suggestion https://github.com/matiastucci/vue-input-tag/issues/78

But I'm not planning on implementing this for now. Feel free to open a PR though.
