### ISSUE TITLE
Allowing duplicate tags

### ISSUE THREAD

**Issue by Fusseldieb** [matiastucci/vue-input-tag#79]
Hi,

is there a option to allow duplicate tags. In my application I need to specity the direction of some things, like "L,R,R,L,R,L,L,R", but with this current release it doesn't seem possible.

I also searched for open or closed issues and one person is "redirecting" to another issue, which is redirected to another issue, and so on. Without actually answering this question. It's a mess.

If there's a answer for the current release, it would be great.

EDIT: I've seen that a pull request is open for that, but it was not accepted due to some reason. Why?

**Comment by matiastucci** [comment]
It's merged and published. Thanks for the feedback 👍
