### ISSUE TITLE
How do I continue to use the previous version?

### ISSUE THREAD

**Issue by max-kut** [matiastucci/vue-input-tag#83]
Version of `Vue` I'm using?: 2.5.16

Hi, I used the component from CDN, but after the last update my application broke (I did not use webpack). How do I continue to use the previous version?

**Comment by matiastucci** [comment]
I just added a `unpkg` key to the `package.json` to expose the UMD module. You can use it like this: https://github.com/matiastucci/vue-input-tag/blob/master/README.md#cdn
