### ISSUE TITLE
Array with properties On Datasource

### ISSUE THREAD

**Issue by TioWidow** [matiastucci/vue-input-tag#84]
Hello, sorry for the inconvenience but I wonder if it is possible to use a Array with properties as a datasource and specify a property of the array as the item that will be the Label of the tag.

Something like in this example:

```
<input-tag   v-model="datasource" :tags.sync="text" > </input-tag>

datasource: [ {text:'abc', value:123},{text:'zxc', value:456} ]

```

Version of `Vue` I'm using?: __2.0___

Version of `vue-input-tag` I'm using?: ___last__

Small [JSFiddle](https://jsfiddle.net) showing the issue: _____

**Comment by oakdays** [comment]
@TioWidow If I understood the issue correctly, you could simply use a `v-for` for that to create a tag for each array element. Then, there would be no need for the feature you proposed.

```
<input-tag 
  v-for="(obj, index) in array"
  :key="index"
  v-model="obj.value"
  :tags.sync="text">
  {{ obj.text }}
</input-tag>
```

**Comment by matiastucci** [comment]
Hi, currently it's not possible to do that. I'm not planning in adding that feature. But you are welcome to create a PR. Thanks!
