### ISSUE TITLE
CDN not working

### ISSUE THREAD

**Issue by oakdays** [matiastucci/vue-input-tag#90]
`Vue` version: 2.5.17 . 
`vue-input-tag` version: 2.0.0

Small [JSFiddle](https://jsfiddle.net) showing the issue: https://jsfiddle.net/eywraw8t/409731/

CDN import doesn't seem to work.

In the console this is seen: `Refused to execute script from 'https://unpkg.com/vue-input-tag@2.0.0/dist/vueInputTag.umd.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.`

**Comment by matiastucci** [comment]
🤦‍♂️ thanks for reporting! It's fixed now in the 2.0.1: https://jsfiddle.net/eywraw8t/409731/
