### ISSUE TITLE
How to refresh v-model maually?

### ISSUE THREAD

**Issue by jiangzhen1984** [matiastucci/vue-input-tag#91]
Version of `Vue` I'm using?: _2.5.16____
Version of `vue-input-tag` I'm using?: _2.0.1__

Hello:
    Maybe it's not a issue, I just want to know how to manually refresh tags?
Scenario Description:
   
step１ create {
    get value by ajax
}

step 2. computed: {
      Initialize form values, at this time maybe ajax request not finish yet.
      Some time get default value for initialization 
}

**Comment by matiastucci** [comment]
I'm not sure if I understand. When you use the component you pass your array of tags doing `v-model="tags"`. If you want to change your the tags that the input is showing you just need to update your component's data tags prop. If this not answers your question, can you create a [JSFiddle](https://jsfiddle.net) with an example, please? and I'll reopen the issue. Thanks.

**Comment by jiangzhen1984** [comment]
Hello:

 Please let me re-open this question for double confirm:

Code snapshot,  doesn't refresh tags for display.

<input-tag placeholder="添加显示标签" v-model="articleForm.tags"></input-tag>

250         created() {
....
....                    //send ajax request to back-end server
258                 this.$store.dispatch('getArticleDetail', id).then(res => {
259                     const pDetail = this.$store.state.article.articleDetail;
.....
267                     this.articleForm.tags = pDetail.tags;  <==== update tags v-model
268                     this.articleForm.title = pDetail.title;
269                     this.articleForm.content = pDetail.content;
270                     }
271                 });
272             }

**Comment by matiastucci** [comment]
I don't think it's a bug related to the library. Again, please create a [JSFiddle](https://jsfiddle.net) with an example so I can reproduce it. Also, if you paste code here, at least try to format it nicely. Remove the line numbers for example. You can use a ``` block in Markdown to show the code in a nice way. Thanks.

**Comment by manasvi-kuliza** [comment]
Hi, I am having the same issue. If I am using a value defined in data observables, then it shows up in the input-tag. But if I am getting the value through ajax call, it is not reflected in the input-tag. Please check my fiddle [https://jsfiddle.net/6Lmvuenk/](url) and let me know what can be done. Thanks

**Comment by torresdaniel11** [comment]
i do think this is a but with the library, if i do something like add a v-if in the tag, and toggling the data, then the changes in the v-model will apply to the element. I think the library is missing `watch` for the prop
