### ISSUE TITLE
how can i controll event?

### ISSUE THREAD

**Issue by halrequin** [matiastucci/vue-input-tag#92]
Version of `Vue` I'm using?: 2.5.2

Version of `vue-input-tag` I'm using?: 2.0.1

Small [JSFiddle](https://jsfiddle.net) showing the issue: _____

i want to add method for v-on:change or v-on:blur, but it can't run method
here is my code
```
<input-tag v-model="row.item.synonyms" @change="myMethod">
</input-tag>

<input-tag v-model="row.item.synonyms" @blur="myMethod">
</input-tag>
```
could you tell me what can i do?

**Comment by halrequin** [comment]
also, when i sort data using by key, that data changed without tag.
how can i fix it?

**Comment by matiastucci** [comment]
- When there is a change, [`@input` should work](https://github.com/matiastucci/vue-input-tag/blob/master/src/components/InputTag.vue#L160).
- For the blur you need to add a ref: https://vuejs.org/v2/api/#ref. Please, [search in the issues](https://github.com/matiastucci/vue-input-tag/pull/49#issuecomment-361970969) before creating a new one.

About the sort, please create another issue with a JSFiddle example.
