### ISSUE TITLE
tags list is not updated if the v-model is updated after vue-input-tag init

### ISSUE THREAD

**Issue by serge1peshcoff** [matiastucci/vue-input-tag#95]
Version of `Vue` I'm using?: 2.5.21 (latest from unpkg.me)
Version of `vue-input-tag` I'm using?: 2.0.1 (latest from unpkg.me)

I couldn't make JSFiddle work, so I'll just post the example to reproduce it here:

HTML:

```html
<!doctype html>
<html>
  <head>
  </head>
  <body>
    <div id="app">
      <input-tag placeholder="Add Tag" v-model="tags"></input-tag>
    </div>
    <script src="https://unpkg.com/vue-input-tag"></script>
    <script src="https://unpkg.com/vue">  </script>
  </body>
</html>
```

JS

```js
Vue.component('input-tag', vueInputTag.default)

new Vue({
  el: "#app",
  data: {
    tags: ['start', 'data']
  },
  mounted () {
     setTimeout(() => {
       this.data.push('new')
       console.log('pushed new data, data=', this.data)
     }, 1000);
    
    setTimeout(() => {
       this.data = ['new', 'data']
       console.log('updated data, data=', this.data)
     }, 3000);
  }
})
```

Expected: the `<input-tag>`'s tags list should be updated.
What happens: it doesn't in both cases.

I've fixed that for myself by just rendering the `<input-tag>` after the data would be set (in my case it's an HTTP request, not a `setTimeout()`, but it would be nice to have it auto-updated when I update the prop that I pass as `v-model`. Is that feasible?

Thanks a lot!

**Comment by matiastucci** [comment]
Yup, https://github.com/matiastucci/vue-input-tag/pull/94 should fix it. Thanks for reporting it.

**Comment by serge1peshcoff** [comment]
yeah, checked it, works flawlessly for me. Thanks a lot!

**Comment by AkshatSrivastava2** [comment]
@matiastucci Didn't work out for me. Any other solution?

**Comment by matiastucci** [comment]
I just merged and released this: https://github.com/matiastucci/vue-input-tag/pull/94. Open the issue again if you need.
