### ISSUE TITLE
Input Tag is not binding properly with v-model

### ISSUE THREAD

**Issue by invshakil** [matiastucci/vue-input-tag#96]
Version of `Vue` I'm using?: v2.3

Version of `vue-input-tag` I'm using?:2

Here I am passing the data by v-model to the input tags. but it is not showing. please check the screenshot. how can i solve this.

![image](https://user-images.githubusercontent.com/26332795/50426273-3baf7200-08b4-11e9-83c7-e9bc693f7c5c.png)

**Comment by matiastucci** [comment]
I think it's related to this: https://github.com/matiastucci/vue-input-tag/pull/94

**Comment by matiastucci** [comment]
#94 should solve this. It's released in 2.0.2.
