### ISSUE TITLE
First change

### ISSUE THREAD

**Issue by mysuf** [matiastucci/vue-input-tag#97]
Version of `Vue` I'm using?:  2.5.21

Version of `vue-input-tag` I'm using?: 2.0.1

First added/removed tag does not change model immediately. If you use @update:tags="printModel", model is unchanged. When you print model value in setTimeout, it returns already changed value. It seems that input event is emitted after update:tags which is wrong order. If update:tags is dispatched before input event, it does not reflect changes on model yet. Dunno why it happens only first time..

EDIT: v-on:input="printModel" works as expected.

**Comment by matiastucci** [comment]
https://github.com/matiastucci/vue-input-tag/pull/94 should fix this.
