### ISSUE TITLE
Values are not trimmed

### ISSUE THREAD

**Issue by serge1peshcoff** [matiastucci/vue-input-tag#98]
Version of `Vue` I'm using?: 2.5.16
Version of `vue-input-tag` I'm using?: 2.0.1

So when I type "first", then a comma, then a space, then a "second", the values I have are `["first", " second"]` instead of `["first", "second"]` (note the space at the beginning of "second").

Can I trim it somehow by specifying an option when creating a component or something like that?

Thanks in advance!

**Comment by matiastucci** [comment]
https://github.com/matiastucci/vue-input-tag/pull/101/files should give you the flexibility to trim it.
